---
title: "Infected and Active Cases Trend By States of 100days of COVID-19 in Nigeria"
author: "Babatunde Adebayo"
date: "6/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r message=FALSE, warning=FALSE}
library(tidyverse, warn.conflicts = F)
library(ggrepel)
library(glue)
library(ggsci)
library(png)
library(ggtext)
library(gridtext)#library(grid)
library(patchwork)
library(showtext) #https://github.com/yixuan/showtext
```

## Fonts
Custom google fonts using showtext package
```{r fonts, echo=FALSE, message=FALSE, warning=FALSE}
font_add_google("Fredoka One", "fredoka") # Title
font_add_google("Muli", "muli") # Subtitle
font_add_google("Cagliostro", "cagliostro") # Annotation
font_add_google("Poppins", "poppins") # Annotation
font_add_google("Raleway", "raleway") # Annotation

showtext_auto() # Use showtext
```

## Data
```{r Load Data, message=FALSE, warning=FALSE, Message=FALSE}
df_daily_case_by_state_region <- read_csv('../data/df_daily_case_by_state_region.csv')

length(unique(df_daily_case_by_state_region$Date))

df100days <- df_daily_case_by_state_region %>% select(Date, States, Confirmed_Cases, Active) #%>% filter(States!='Cross River')

df100days
```
```{r}
df100days <- df100days %>% left_join(
  distinct(df_daily_case_by_state_region, Date) %>% 
  mutate(time = c(1:100))
)
```


# Plot
```{r theme}
custom_minimal_theme = theme_minimal() +
  theme(
    # axis.text.x = element_text(colour = 'gray87', size = 9, face = 'bold'),
    # axis.text.y = element_text(colour = 'gray87', size = 8),
    strip.background = element_rect(fill = 'gray84', color=NA),
    strip.text = element_text(face = 'bold'),
    axis.title = element_text(face='bold'),
    # axis.line.x = element_line(size=0.5,color='gray43'),
    # axis.ticks.x = element_line(size=0.5,color='gray43'),
    # panel.grid = element_blank()
    # panel.background = element_rect(color = 'black', colour = NA),
    # plot.background = element_rect(fill = 'black', colour = 'black')
  ) 
```

```{r infected_states, fig.height=9.4, fig.width=7.5}
library(scales)
p_infected_state <-  
  df100days %>%
  filter(States != "Cross River") %>%
  ggplot(aes(x = time, y = Confirmed_Cases)) +
  geom_line(color = 'black', size = 1) +
  geom_line(aes(x = time, y = Active),color = 'red', size = 1) +
  # scale_y_continuous(breaks= pretty_breaks())  +
  labs(x = 'time', y = "Number of Persons") +
  custom_minimal_theme +
  facet_wrap( ~ States, ncol=4, scales = 'free')
# p_other_state
```



```{r}
png(filename = 'infected and active covid-19 in Nigeria (100days).png', height=9.5, width=7.7, units = 'in')
p_infected_state
dev.off()
```
















# Previous
## Plot
```{r}
line_color ='#B37400'
avg_color = "#B30300"
custom_dark_theme = theme_dark() +
  theme(
    axis.text.x = element_text(colour = 'gray87', size = 9, face = 'bold'),
    axis.text.y = element_text(colour = 'gray87', size = 8),
    strip.background = element_rect(fill = '#1A1000'),
    strip.text = element_text(face = 'bold'),
    axis.line.x = element_line(size=0.5,color='white'),
    axis.ticks.x = element_line(size=0.5,color='white'),
    panel.grid = element_blank(), 
    panel.background = element_rect(fill = 'black', colour = NA),
    plot.background = element_rect(fill = 'black', colour = 'black')
  ) 
```

```{r Lagos_plot, fig.height=7, fig.width=9}
## Lagos
p_lagos <- df_daily_case_by_state_region %>%
  filter(States == "Lagos") %>% 
  ggplot(aes(x = Date, y = Confirmed_Cases)) +
  geom_line(color = line_color, size = 1) + 
  # stat_summary(fun = max, geom = "point", size = 5, color='white') +
  geom_hline(aes(yintercept = nationwide_avg), color = avg_color, size = 0.6) + #990300
scale_y_continuous(limits = c(0,6000), breaks = c(0,seq(1000,6000,by=1000))) +
  labs(x = NULL, y = NULL) + 
  custom_dark_theme +
  facet_wrap( ~ States, ncol=6)  
p_lagos
```

```{r fig.height=7, fig.width=9}
## Other States
p_other_state <-  df_daily_case_by_state_region %>%
  filter(States != "Lagos") %>% 
  ggplot(aes(x = Date, y = Confirmed_Cases)) +
  geom_line(color = line_color, size = 1) +
  geom_hline(aes(yintercept = nationwide_avg), color =avg_color, size = 0.6) + #990300
  labs(x = NULL, y = NULL) +
  custom_dark_theme + 
  facet_wrap( ~ States, ncol=6)
```

```{r}
## Legend Annotation
library(grid)
gp = gpar(col = "gray60", fontsize=9)
grob_txt1 <- richtext_grob(text="**Confirmed Cases**",gp=gp, halign = 0,hjust = 0 )
grob_txt2 <- richtext_grob(text="**Nationwide Average**",gp=gp, halign = 0,hjust = 0)
df <- tibble(x=1:5, y=1:5)

p_legend <- 
df %>% ggplot(aes(x,y))+
  annotate("segment",  x=1, xend=2, y=1.5, yend=1.5, colour=line_color, size=1)  +
  annotate("segment",  x=1, xend=2, y=1, yend=1, colour=avg_color, size=0.9)+
  annotation_custom(grob = grob_txt2, xmin = 1.5,xmax = 2.7,ymin = 1,ymax = 1) +
  annotation_custom(grob = grob_txt1, xmin = 1.5,xmax = 2.7,ymin = 1.5,ymax = 1.5) +
  coord_cartesian(xlim = c(1, 2.5),  clip = 'off') +
  custom_dark_theme +
  theme(
    axis.text.x= element_blank(),
    axis.text.y= element_blank(),
    axis.line.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank()#,
    # plot.margin = margin(1,1,1,1,'pt')
    )

# p_legend
```

## Merge
```{r}
p_lagos2 <- p_lagos+ 
  annotation_custom(ggplotGrob(p_legend), xmin = as.Date("2020-06-02", "%Y-%m-%d"), xmax =as.Date("2020-06-30", "%Y-%m-%d"), ymin = 2000, ymax = 5000) +
  coord_cartesian(clip = 'off') +
  theme(plot.margin = unit(c(0,12,0,0),'lines'))
# p_lagos2
```

```{r  fig.height=9, fig.width=9}
layout <- "
###AAAA#
BBBBBBBB
"
P_patched <- p_lagos2+p_other_state+
  plot_layout(heights = c(0.9, 4),design = layout) &
  theme(plot.background = element_rect(fill='black', colour = 'black'))

P_patched
```

## Annotation

```{r}
# p_lagos + 

```


