---
title: "100 Days of COVID-19 in Nigeria - Map 02: Confirmed COVID-19 Cases by States (and FCT)"
author: "Babatunde Adebayo"
date: "6/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(ggtext)
library(showtext)
```

```{r message=FALSE, warning=FALSE}
##############################################################
# DEMO 1 - Generate a 2D map plot with ggplot2
##############################################################
df_daily_case_by_state_region <- read_csv('../data/df_daily_case_by_state_region.csv')


# Cleaning
data_20200605 <- df_daily_case_by_state_region %>% 
  select(!contains("Daily")) %>% 
  filter(Date == sort(unique(Date))[100] )  %>% # filter day 100
  select(!c("Active","Recovered","Death","Confirmed_Cases_cum"))%>% 
  group_by(Geopolitical_Zone) %>% 
  mutate(region_sum = sum(Confirmed_Cases)) %>% 
  ungroup() 

#Spatial
nig_shp <- st_read("./data/Nigeria_OCHA/Admin_1/nga_polbnda_adm1_1m_salb.shp") 

nig_shp <- nig_shp %>% 
  select(ADM1_NAME ,geometry) %>% 
  rename(States = ADM1_NAME) %>% 
    mutate(States = case_when(
      States == 'Akwa lbom' ~ 'Akwa Ibom',
      States == 'Federal Capital Territory' ~ 'FCT',
      TRUE ~ States
    )) %>%  
  mutate(centroid = st_centroid(geometry)) %>%
  mutate(
    lon = st_coordinates(.$centroid)[,1],
    lat = st_coordinates(.$centroid)[,2]
  )


# Together
map_data <- full_join(nig_shp, data_20200605)
names(map_data)
```


#Map
```{r} 

map_bg <- map_data %>%   
            ggplot()+ 
            geom_sf(aes(fill = Confirmed_Cases), color='#FFFFFF') + # border color 
            scale_fill_gradient(limits=range(map_data$Confirmed_Cases), 
                                low="#FFF3B0", high="#C65315") + #Confirmed Cases Density Color             # geom_sf_text(aes(x = lon, y=lat-2,label=States), 
            # size =3, fontface='bold', color="grey10")+
          theme( axis.line=element_blank(),
                axis.text.x=element_blank(), axis.title.x=element_blank(),
                axis.text.y=element_blank(), axis.title.y=element_blank(),
                axis.ticks=element_blank(),
                legend.position = "none", 
                panel.grid = element_blank(),
                panel.background = element_blank() 
                )
  
  map_bg
```


```{r}
# Save as PNG
xlim = ggplot_build(map_bg)$layout$panel_scales_x[[1]]$range$range # 2.67 14.68
ylim = ggplot_build(map_bg)$layout$panel_scales_y[[1]]$range$range # 4.28 13.9
ggsave('map_bg.png', width = diff(xlim)*2, height = diff(ylim)*2, units = "cm") #480 384.9553

# 114 114  # 22.2 22.6 #24.25537 16.35597
```

##############################################################
# DEMO 2 - Transform the 2D plot into 3D plot with rayshader
##############################################################

```{r}
# Read Background Image
library(png)
ng_map_bg = readPNG('map_bg.png')
```

```{r}
# 2D Plot
library(ggplot2)
library(grid)
nig_cc = ggplot(map_data) + 
  annotation_custom(rasterGrob(ng_map_bg, width=unit(1,"npc"), height=unit(1,"npc")), 
                    -Inf, Inf, -Inf, Inf) + # Background
  xlim(xlim[1],xlim[2]) + # x-axis Mapping
  ylim(ylim[1],ylim[2]) + # y-axis Mapping
  geom_point(aes(x=lon, y=lat, color=Confirmed_Cases), size = 2)+ # Points
  scale_colour_gradient(name = 'Confirmed Cases', 
                        limits=range(map_data$Confirmed_Cases), 
                        low="#FDD3CE", high="#9A323E") + # Price Density Color
  theme(axis.line=element_blank(), 
        axis.text.x=element_blank(), axis.title.x=element_blank(),
        axis.text.y=element_blank(), axis.title.y=element_blank(),
        axis.ticks=element_blank(),  
        panel.background = element_blank()) # Clean Everything

nig_cc
ggsave('confirmed_cases.png', width = diff(xlim)*2, height = diff(ylim)*2, units = "cm")
```

### 3D Plot
```{r}
# 3D Plot
library(rayshader)
plot_gg(nig_cc, multicore = TRUE, width=5, height=5, scale=300, windowsize=c(1450,876))
Sys.sleep(5)

# Render Video
# Video 1
phivechalf = 30 + 60 * 1/(1 + exp(seq(-7, 20, length.out = 180)/2))
phivecfull = c(phivechalf, rev(phivechalf))
thetavec = 0 + 45 * sin(seq(0,359,length.out = 360) * pi/180)
zoomvec = 0.45 + 0.2 * 1/(1 + exp(seq(-5, 20, length.out = 180)))
zoomvecfull = c(zoomvec, rev(zoomvec))
render_movie(filename = 'output1c', type = "custom", frames = 360,  phi = phivecfull, zoom = zoomvecfull, theta = thetavec,)


# Close Windows
rgl.close()
render_snapshot(clear = TRUE)
```
### Another Function
```{r}
plot_gg(nig_cc, multicore = TRUE, width=5,height=5,scale=250,windowsize=c(1450,876))
# Video 2
transition_values <- function(from, to, steps = 10, one_way = FALSE, type = "cos") {
  if (!(type %in% c("cos", "lin"))){stop("type must be one of: 'cos', 'lin'")}
  range <- c(from, to)
  middle <- mean(range)
  half_width <- diff(range)/2
  if (type == "cos") {scaling <- cos(seq(0, 2*pi / ifelse(one_way, 2, 1), length.out = steps))}
  else if (type == "lin"){
    if (one_way) {xout <- seq(1, -1, length.out = steps)} 
    else {xout <- c(seq(1, -1, length.out = floor(steps/2)), seq(-1, 1, length.out = ceiling(steps/2)))}
    scaling <- approx(x = c(-1, 1), y = c(-1, 1), xout = xout)$y }
  middle - half_width * scaling
}
theta <- transition_values(from = 0, to = 360, steps = 360, one_way = TRUE, type = "lin")
phi <- transition_values(from = 10, to = 70, steps = 360, one_way = FALSE, type = "cos")
zoom <- transition_values(from = 0.4, to = 0.8, steps = 360, one_way = FALSE, type = "cos")
render_movie(filename = 'output2AA', type = "custom", frames = 360,  phi = phi, zoom = zoom, theta = theta)

# Close Windows
rgl.close()
```

