---
title: "100 Days of COVID-19 in Nigeria - Map 01: Confirmed COVID-19 Cases by States (and FCT)"
author: "Babatunde Adebayo"
date: "6/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Map of Nigeria showing the distribution of cumulative COVID-19 Confirmed Cases by Geopolitical Zones

## Packages
```{r packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(ggtext)
library(showtext)
library(RColorBrewer)
#library(here)
```

## Fonts
```{r fonts}
#font_add_google("Poppins", "poppins") # Annotation
#showtext_auto() # Use showtext
```

## Load Data
```{r load_data, message=FALSE, warning=FALSE} 
data_MaxDay <- read_csv("../data/df_nigeria_MaxDay.csv") %>% 
                         select(States,Confirmed_Cases, Geopolitical_Zone) 

color_df = tibble(Geopolitical_Zone = c("South West","North West", "North Central",
                                        "North East","South South" ,"South East"),
                  colours = c("#f8766d","#00ba38","#619cff","#02ffde","#f564e3","#b79f00"))

data_MaxDay <-  data_MaxDay %>%
                left_join(color_df) %>% 
              mutate(
                cc_range = case_when(
                   Confirmed_Cases == 0 ~ "0",
                   Confirmed_Cases <= 100 ~ "1 - 100",
                   Confirmed_Cases <= 500 ~ "101 - 500",
                   Confirmed_Cases <= 1000 ~ "501 - 1,000",
                   Confirmed_Cases <= 10000 ~ "1,001 - 10,000" ,
                   Confirmed_Cases > 10000 ~ ">10,000" 
                   ),
                cc_range = factor(cc_range,levels = c("0","1 - 100","101 - 500","501 - 1,000","1,001 - 10,000",">10,000")),
                label_color = case_when(
                  States == "Lagos" ~ "white",
                  TRUE ~ "grey40"
                )
              )

```
 


## Load Nigeria Shape File
Data source: https://data.humdata.org/dataset/nigeria-admin-level-0-1-and-2-administrative-boundaries
```{r message=FALSE, warning=FALSE, include=FALSE}
nig_shp <- st_read("./data/Nigeria_OCHA/Admin_1/nga_polbnda_adm1_1m_salb.shp") 

nig_shp <- nig_shp %>% 
  select(ADM1_NAME ,geometry) %>% 
  rename(States = ADM1_NAME) %>% 
    mutate(States = case_when(
      States == 'Akwa lbom' ~ 'Akwa Ibom',
      States == 'Federal Capital Territory' ~ 'FCT',
      TRUE ~ States
    )) %>%  
  mutate(centroid = st_centroid(geometry)) %>%
  mutate(
    lon = st_coordinates(.$centroid)[,1],
    lat = st_coordinates(.$centroid)[,2]
  )


# Together
map_data <- full_join(nig_shp, data_MaxDay)
# names(map_data)
```




## Plot 1
```{r theme}
custom_black_theme <- theme_void() +
  theme(
    panel.background = element_rect(color =NA,fill='black'),
    plot.background =  element_rect(color =NA,fill='black'),
    plot.margin = margin(t = 1,r = -25,b = 1,l = -25,unit = 'cm'),
    # Legend
    legend.position = "top",
    legend.justification = 'center',
    legend.text = element_text(family = "poppins", face = 'bold',
                               color = "white", size = 10),
    legend.key.width = unit(5.2, "lines"),
    legend.key.height = unit(0.8, "lines") 
  )
```

# 
```{r plot1, fig.width = 9, fig.height = 6.9} 
col_range = c('#FFFFFF',colorRampPalette(brewer.pal(7,"Blues"))(7)[2:5],"#001F47")

map_data  %>% 
  ggplot() +
  geom_sf(color=NA, fill='white') + 
  geom_sf(aes(fill = cc_range), color = "white", 
          alpha = 0.65,  size = 0.3) +
  scale_fill_manual(values = col_range)  +
  guides(fill = guide_legend(title.position = "top", 
                             title.hjust = 0.5, nrow = 1,
                             label.position = "top"))+
  geom_sf_text(aes(label=States, color=colours), size =3, fontface='bold')  +#grey99
  scale_color_identity() +
  # coord_sf(expand = F) +
  custom_black_theme

ggsave(filename = "map_train.png", device = 'png')
```

## Plot 2
```{r}


```


```{r nigeria region , fig.width = 9, fig.height = 6.9}
p1 = nig_plot_data %>%   
  ggplot()+ 
  geom_sf(aes(fill = colours), alpha=0.6,color='grey50') +
  geom_sf_text(aes(label=States), size =2.5, color='grey99', fontface='bold') 

p1 + scale_y_continuous(expand = c(0.0, 0.0)) + scale_x_continuous(expand = c(0, 0)) 

p1 +
    theme(
      plot.background = element_rect(fill='black'),
      panel.background = element_rect(fill='black'),
      panel.grid = element_blank(),
      legend.position = 'none',
      axis.title = element_blank(),
      axis.text = element_blank(), 
      plot.margin = margin(0, 0, 0, 0) #0, -89, 0, 0
    )
  # theme_custom_black
p1
```



